### ISSUE TITLE
Support for video files

### ISSUE THREAD

**Issue by rohantarai** [yifaneye/react-gallery-carousel#14]
This is the best carousel library. but i would like to request a feature to support video files.

**Comment by yifaneye** [comment]
Hi @rohantarai ! Thank you for raising this issue up! 😄

Thank you for your appreciation! I will add support for video files and publish a new version before the end of next week. 👨🏻‍💻 Rest assured that there will be no breaking changes. I will notify you for the new version.

**Comment by rohantarai** [comment]
Hey @yifaneye ,
Thanks for responding to my request. i am happy to see that you accepted it as an enhancement. Looking forward to use the video feature! :)

**Comment by yifaneye** [comment]
Hi @rohantarai ,
You're welcome! You will see the video feature before the end of next week.

**Comment by yifaneye** [comment]
Hi @rohantarai ,

Issue #27 reminded me that you can use the "children" prop for placing video files into the carousel. Currently, the "children" prop is served as an option for "user-managed" slides. Since I believe that developer users may have their own markup and styles to be placed in each slide.

For example, you can place your video file here to replace the text in the slide https://github.com/yifaneye/react-gallery-carousel/blob/c12338a48806e1149cbeddf43e5bf65cf286a008/example/src/components/Carousel1.js#L48

Hope it helps!

**Comment by rohantarai** [comment]
@yifaneye Hey sorry for late reply. As in the documentation it was not mentioned about using children prop to show video files, so i thought to tell you about adding feature for video files.

**Comment by yifaneye** [comment]
Hi @rohantarai !

Thank you for pointing this out! You asked a very good question. 😀

I will enhance the documentation to mention about "using children prop to show video files".
