### ISSUE TITLE
Need caption for {children} elements

### ISSUE THREAD

**Issue by sergru** [yifaneye/react-gallery-carousel#27]
I use react-gallery-carousel with {chidren} to show different types of items in carousel (images, video and audio media).
It works fine but I cannot add the caption for the item.

**Solution I'd like**
Add special component <CarouselItem> that has required attributes like **caption** and supports {children} to handle user defined inner html as usual React component.

**Comment by yifaneye** [comment]
Hi @sergru , 

Thank you for using react-gallery-carousel! 

Currently, the children is served as an option for "user-managed" slides. Since I believe that developer users may have their own markup and styles to be placed in each slide. 

I am sorry to inform you that I am not going to add caption at this stage since that will introduce the need to allow users to customize the caption in a lot of ways. However, I am sure that you can make caption similar to the default caption for the managed image slides. 

The markup can be found at https://github.com/yifaneye/react-gallery-carousel/blob/c12338a48806e1149cbeddf43e5bf65cf286a008/src/components/Widgets/Widgets.js#L196

The styles can be found at https://github.com/yifaneye/react-gallery-carousel/blob/c12338a48806e1149cbeddf43e5bf65cf286a008/src/components/Widgets/Widgets.module.css#L25

Hope it helps!
