### ISSUE TITLE
Setting dynamic images, makes the slideshow only show the first image

### ISSUE THREAD

**Issue by bitnosis** [yifaneye/react-gallery-carousel#28]
const images = [900, 800, 700, 600, 500].map((size) => ({
        src: `https://placedog.net/${size}/${size}`
      }));

    useEffect(() => {
        setDynamicImages(images);
        return () => {};
    }, [setDynamicImages, images]);

**Comment by yifaneye** [comment]
Hi @bitnosis ! Thank you for raising this issue up! 😄

I admit that the example code is not really good. At that time, I want to show that my carousel can fit images with any size. The images are actually different but they look the same because they are all chopped from the same image. Therefore, in fact this has not been because of dynamic images. 😅

I think 
`
const images = [9, 8, 7, 6, 5].map((number) => ({
    src: `https://placedog.net/${number}00/${number}00?id=number`
}));
`
would be a much better example.

Here is a screenshot of the carousel with the `images` above.
![SS 2021-05-08 at 00 22 39](https://user-images.githubusercontent.com/49315663/117463955-89b00680-af93-11eb-8c15-c7e8ba89763a.jpg)

I will update the example in the next version. 😃
