### ISSUE TITLE
How to use array of photos in carousel user managed slide ?

### ISSUE THREAD

**Issue by AnmolChhabra98** [yifaneye/react-gallery-carousel#53]
Hi yifaneye,

I am trying to make , user managed slide from an object which is having different kind of values and Photos[] array is one of among them but I am unable to use my Photos[] properly , when I used it with the map function of array it is showing photos but it is overlapping them on other slides too . Can you please tell me how can I do this properly so that each photo comes on different slide ?

Thanks,

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 ! Thank you for raising this issue up. 😀

I understand that you are currently experiencing problems! Would you like to show us your code, the current behaviour and your expected behaviour? Thanks!

In general, user-managed slides are through the `children` prop. They are HTML element(s) to be placed into the carousel for user-managed slides. It (they) will be placed only if the 'images' prop is falsy. There is a precedence here, as in images > children.
