### ISSUE TITLE
dotButtons has an index undefined when loading dynamic images

### ISSUE THREAD

**Issue by BarthelemyPassinCauneau** [yifaneye/react-gallery-carousel#7]
**Describe the bug**
I load images from my back-end dynamicaly in the carousel. I want to display the dotButtons but at the firsts renders, the console is printing "Warning Failed prop type: The prop `curIndex` is marked as required in `DotButtons`, but its value is `undefined`."

**To Reproduce**
1. Load images asynchronously
2. Turn on the dotButtons display in the carousel
4. See the error in the console

**Expected behavior**
It doesn't crash the app and it keep the expected behavior when I navigate in the carousel (the active dot is correct, the unactives ones aswell and the total is good). But it still print a problem in the console.

**Desktop :**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version 87.0

**Comment by yifaneye** [comment]
Hi @BarthelemyPassinCauneau ! Thank you for bringing this issue up! 😄

 I am glad that your app still works and still have the expected behaviour! 😌

When I was testing things, I defined the images straightway most of the times. I set the required props too strict in prop-types. 

I will go through each of PropTypes validation carefully in the setting of dynamically fetching images from the back-end. I will make sure there are no more errors due to PropTypes validation.

I will get this issue fixed and publish a new version before the end of this week. 👨🏻‍💻 I will notify you for the new version!

**Comment by BarthelemyPassinCauneau** [comment]
Hi ! Thanks for the fast reply 😄 !
I'm glad you'll be able to fix this little issue soon, your carousel is very excellent (the swipe with the mouse is sooo smooth 😊 instead of many other ones) and deserve to be used by a lot of dev.
Good job and keep it up !

**Comment by yifaneye** [comment]
You're welcome. 😊

Thank you for your encouragement! 

Your positive feedbacks keep me to go forward and beyond! 🙌

**Comment by yifaneye** [comment]
Hi @BarthelemyPassinCauneau ! I fixed this issue and published a new version (v0.1.4). Please install this new version by npm update react-gallery-carousel. In this version, I fixed this issue by defining default props.

**Comment by BarthelemyPassinCauneau** [comment]
Hi ! It works perfectly, thanks for the (very) fast fix. Have a great day ! 😄

**Comment by yifaneye** [comment]
@BarthelemyPassinCauneau Nice to hear! You're welcome! You too!
