### ISSUE TITLE
shouldMaximizeOnClick doesn't work

### ISSUE THREAD

**Issue by Ruslan27032000** [yifaneye/react-gallery-carousel#74]
I have Carousel with shouldMinimizeOnClick and shouldMaximizeOnClick. In mobile version maximize working great, but if I click on toggle device toolbar and click on image it doesn't work.

1. Go to https://yifaneye.github.io/react-gallery-carousel/
2. Open console and click on "Toggle device toolbar". Choose Some phone(for example IPhone XR)
3. Scroll down to carousel with shouldMaximizeOnClick

![image](https://user-images.githubusercontent.com/40733142/169230398-5e658bca-f7c0-4ddb-a4cc-ee7a928fd1ef.png)
![image](https://user-images.githubusercontent.com/40733142/169230455-ca4c3617-c33f-41e0-bce2-f00f3e1cf4e7.png)

**Comment by yifaneye** [comment]
Hi @Ruslan27032000 Thanks for raising this issue up! I will investigate!

**Comment by yifaneye** [comment]
Hi @Ruslan27032000 ! 

This issue is because the touch event is recognized additionally as a mouse event on simulated mobile devices (e.g. Toggle Device Toolbar on Chrome).

It is now fixed in v0.3.0. See the gif below. 😁
![issue-74-fixed](https://user-images.githubusercontent.com/49315663/195961904-acda1714-d9d9-45dd-89c9-48d02572aa22.gif)
